services:
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: codemate
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            command: --bind-address=0.0.0.0
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata:
